// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OrderInventoryPlatform.Infrastructure.Persistence;

#nullable disable

namespace OrderInventoryPlatform.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260321130000_AddInventoryMovementReason")]
partial class AddInventoryMovementReason
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.25")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("OrderInventoryPlatform.Domain.Catalog.Product", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<decimal>("Price")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<int>("ReorderThreshold")
                .HasColumnType("integer");

            b.Property<string>("Sku")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.HasKey("Id");

            b.HasIndex("Sku")
                .IsUnique();

            b.ToTable("Products");
        });

        modelBuilder.Entity("OrderInventoryPlatform.Domain.Inventory.InventoryItem", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<int>("AvailableQuantity")
                .HasColumnType("integer");

            b.Property<Guid>("ProductId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("ProductId")
                .IsUnique();

            b.ToTable("InventoryItems");
        });

        modelBuilder.Entity("OrderInventoryPlatform.Domain.Inventory.InventoryMovement", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid>("ProductId")
                .HasColumnType("uuid");

            b.Property<int>("Quantity")
                .HasColumnType("integer");

            b.Property<Guid?>("RelatedOrderId")
                .HasColumnType("uuid");

            b.Property<string>("Reason")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<int>("Type")
                .HasColumnType("integer");

            b.HasKey("Id");

            b.HasIndex("ProductId");

            b.HasIndex("RelatedOrderId");

            b.ToTable("InventoryMovements");
        });

        modelBuilder.Entity("OrderInventoryPlatform.Domain.Orders.Order", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("Status")
                .HasColumnType("integer");

            b.HasKey("Id");

            b.ToTable("Orders");
        });

        modelBuilder.Entity("OrderInventoryPlatform.Domain.Orders.OrderLine", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<decimal>("LineTotal")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<Guid>("OrderId")
                .HasColumnType("uuid");

            b.Property<Guid>("ProductId")
                .HasColumnType("uuid");

            b.Property<int>("Quantity")
                .HasColumnType("integer");

            b.Property<decimal>("UnitPrice")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.HasKey("Id");

            b.HasIndex("OrderId");

            b.HasIndex("ProductId");

            b.ToTable("OrderLines");

            b.HasOne("OrderInventoryPlatform.Domain.Orders.Order", null)
                .WithMany("_lines")
                .HasForeignKey("OrderId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
