name: Build and deploy ASP.Net Core app to Azure Web App - orderinventory-api-dennis

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/main_orderinventory-api-dennis.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore solution
        run: dotnet restore ./backend/OrderInventoryPlatform.sln

      - name: Build API project
        run: dotnet build ./backend/src/OrderInventoryPlatform.Api/OrderInventoryPlatform.Api.csproj --configuration Release --no-restore

      - name: Publish API project
        run: dotnet publish ./backend/src/OrderInventoryPlatform.Api/OrderInventoryPlatform.Api.csproj -c Release -o ./backend/publish --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./backend/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_05F4C6FD33C649E5A774A357DE963FC2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B6EF2F6783B84DC5B7404F2F2E8F01C0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9C31648151E8494FA08E2B8B8FE11CC0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'orderinventory-api-dennis'
          slot-name: 'Production'
          package: .
